{
 "title": "Nethermind Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus_ds", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "network", "label": "Network", "query": { "query": "label_values(Network)" } },
   {
    "name": "enode",
    "label": "Instance",
    "query": {
     "query": "label_values({Network=~\"$network\"},Instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Bad Blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nethermind_bad_blocks{Instance=~\"$enode\"}) by (Instance)",
     "legendFormat": "{{Instance}} - Total"
    },
    {
     "expr": "sum(nethermind_bad_blocks_by_nethermind_nodes{Instance=~\"$enode\"}) by (Instance)",
     "legendFormat": "{{Instance}} - By Nethermind nodes"
    }
   ]
  },
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} {{Network}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} {{Runtime}}"
    }
   ]
  },
  {
   "title": "Sync Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} {{SyncType}}"
    }
   ]
  },
  {
   "title": "Pruning Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} {{PruningMode}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} {{Version}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nethermind_sync_time{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Sync Time",
   "type": "stat",
   "description": "Max total time is taken for the node to sync. If the node synced for more than a week ago this value will be equal to 0.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_over_time(((nethermind_sync_time{Instance=~\"$enode\"} > 0)[7d:]))",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Pruning Time",
   "type": "stat",
   "description": "Max total time is taken for the node to complete a pruning process. If the node finished pruning more than a week ago this value will be equal to 0.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_over_time(((nethermind_pruning_time{Instance=~\"$enode\"} > 0)[7d:]))",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  { "title": "Basic Parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sync Peers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_sync_peers{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Sync Peers: {{client_type}}"
    }
   ]
  },
  {
   "title": "Total difficulty",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_total_difficulty{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Last difficulty",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_last_difficulty{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Total difficulty diff",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "increase(nethermind_total_difficulty{Instance=~\"$enode\"}[$__range])",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "$__range_s/increase(nethermind_blocks{Instance=~\"$enode\"}[$__range])",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Traffic (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(nethermind_json_rpc_bytes_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} RPC Sent"
    },
    {
     "expr": "increase(nethermind_json_rpc_bytes_received{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} RPC Received"
    },
    {
     "expr": "increase(nethermind_discovery_bytes_received{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Dscv Sent"
    },
    {
     "expr": "increase(nethermind_discovery_bytes_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Dscv Received"
    },
    {
     "expr": "increase(nethermind_p2pbytes_received{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} P2P Received"
    },
    {
     "expr": "increase(nethermind_p2pbytes_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} P2P Sent"
    }
   ]
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(max without (BuildTimestamp,Commit,Version) (nethermind_version{Instance=~\"$enode\"}) != 0) / 100000",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  { "title": "Engine API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Execution Times & Throughput",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_new_payload_execution_time{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} New Payload"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_forkchoice_upded_execution_time{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} Forkchoice Update"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_mgas_per_sec{Instance=~\"$enode\"} > 0)",
     "legendFormat": "{{Instance}} Throughput"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Total Memory"
    },
    {
     "expr": "dotnet_total_memory_bytes{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Managed Memory"
    },
    {
     "expr": "dotnet_total_memory_bytes{Instance=~\"$enode\"} -   nethermind_memory_used_by_cache{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Managed Memory without pruning cache"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_total_memory_size{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} DB Total Memory"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_block_cache_memory_size{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} DB Blockcache"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_index_filter_memory_size{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} DB Index & Filters"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_memtable_memory_size{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} DB Memtables"
    }
   ]
  },
  {
   "title": "Time in GC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_runtime_time_in_gc{instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Time GC"
    }
   ]
  },
  {
   "title": "Memory Growth (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "deriv(dotnet_total_memory_bytes{instance=~\"$enode\"}[1m]) > 0",
     "legendFormat": "{{Instance}} Managed Memory",
     "target": "*.Nethermind_Runner.*.*.*.*.gauge.*.Process_Physical_Memory"
    }
   ]
  },
  {
   "title": "GC (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Gen {{generation}}"
    }
   ]
  },
  { "title": "Pruning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Caching Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_loaded_from_db_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} DB"
    },
    {
     "expr": "nethermind_loaded_from_rlp_cache_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} RLP Cache"
    },
    {
     "expr": "nethermind_loaded_from_cache_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Node Cache"
    },
    {
     "expr": "nethermind_rlp_cache_hits{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} TrieStore RLP Cache Hits"
    }
   ]
  },
  {
   "title": "Pruning Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nethermind_memory_used_by_cache{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Pruning Levels",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_committed_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Committed"
    },
    {
     "expr": "nethermind_persisted_node_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Persisted"
    },
    {
     "expr": "nethermind_cached_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Cached"
    },
    {
     "expr": "nethermind_replaced_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Replaced"
    },
    {
     "expr": "nethermind_pruned_persisted_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Pruned Persisted"
    },
    {
     "expr": "nethermind_pruned_transient_nodes_count{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Pruned Transient"
    }
   ]
  },
  {
   "title": "Times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_snapshot_persistence_time{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Persistence"
    },
    {
     "expr": "nethermind_pruning_time{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Pruning"
    },
    {
     "expr": "nethermind_deep_pruning_time{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Block processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_last_block_processing_time_in_ms{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} Block time"
    }
   ]
  },
  {
   "title": "GasUsed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_gas_used{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} Block Gas"
    }
   ]
  },
  {
   "title": "Blocks (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_blocks{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Blocks"
    }
   ]
  },
  {
   "title": "Sync Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_sync_peers{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} - {{client_type}}"
    }
   ]
  },
  {
   "title": "State Synced (in bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_state_synced{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} State"
    },
    {
     "expr": "rate(nethermind_state_synced{Instance=~\"$enode\"}[60m])*3600",
     "legendFormat": "{{Instance}} State/h"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_snap_state_synced{Instance=~\"$enode\"})",
     "legendFormat": "{{Instance}} SnapState"
    },
    {
     "expr": "rate(nethermind_snap_state_synced{Instance=~\"$enode\"}[60m])*3600",
     "legendFormat": "{{Instance}} SnapState/h"
    }
   ]
  },
  {
   "title": "SnapSync - Accounts, Storage and ByteCodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_snap_synced_storage_slots{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Storage slots"
    },
    {
     "expr": "nethermind_snap_synced_accounts{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Accounts"
    },
    {
     "expr": "nethermind_snap_synced_codes{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Codes"
    }
   ]
  },
  {
   "title": "Fast Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_fast_headers{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Headers"
    },
    {
     "expr": "nethermind_fast_bodies{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Bodies"
    },
    {
     "expr": "nethermind_fast_receipts{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Receipts"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nethermind_blocks{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Block Number"
    }
   ]
  },
  {
   "title": "CPU time (tracks restarts)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$enode\"}[$__interval])",
     "legendFormat": "{{Instance}} CPU time"
    }
   ]
  },
  { "title": "JSON RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 182 } },
  {
   "title": "JSON RPC (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 183 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "increase(nethermind_json_rpc_successes{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} RPC Successes"
    },
    {
     "expr": "increase(nethermind_json_rpc_errors{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} RPC Errors"
    },
    {
     "expr": "increase(nethermind_json_rpc_request_deserialization_failures{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Deserialization Failures"
    },
    {
     "expr": "increase(nethermind_json_rpc_invalid_requests{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Invalid Requests"
    }
   ]
  },
  {
   "title": "JSON RPC (total)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 190 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nethermind_json_rpc_requests{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} RPC Requests"
    },
    {
     "expr": "nethermind_json_rpc_successes{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} RPC Successes"
    },
    {
     "expr": "nethermind_json_rpc_errors{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} RPC Errors"
    },
    {
     "expr": "nethermind_json_rpc_request_deserialization_failures{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Deserialization Failures"
    },
    {
     "expr": "nethermind_json_rpc_invalid_requests{Instance=~\"$enode\"}",
     "legendFormat": "{{Instance}} Invalid Requests"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Connections (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_incoming_connections{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Incoming Connections"
    },
    {
     "expr": "increase(nethermind_outgoing_connections{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Outgoing Connections"
    },
    {
     "expr": "increase(nethermind_handshakes{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Handshakes"
    },
    {
     "expr": "increase(nethermind_hellos_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Hellos Sent"
    },
    {
     "expr": "increase(nethermind_hellos_received{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Hellos Received"
    },
    {
     "expr": "increase(nethermind_statuses_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Statuses Sent"
    },
    {
     "expr": "increase(nethermind_statuses_received{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Statuses Received"
    }
   ]
  },
  {
   "title": "Pending Txs (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "increase(nethermind_pending_transactions_received{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Received"
    },
    {
     "expr": "increase(nethermind_pending_transactions_known{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Already Known"
    },
    {
     "expr": "increase(nethermind_pending_transactions_discarded{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Discarded"
    },
    {
     "expr": "increase(nethermind_pending_transactions_too_far_in_future{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Too far in future"
    },
    {
     "expr": "increase(nethermind_pending_transactions_too_low_fee{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Too low fee"
    },
    {
     "expr": "increase(nethermind_pending_transactions_added{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Added (all)"
    },
    {
     "expr": "increase(nethermind_pending1559transactions_added{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Added (1559)"
    },
    {
     "expr": "increase(nethermind_pending_transactions_evicted{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Evicted"
    },
    {
     "expr": "increase(nethermind_pending_transactions_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Sent txs"
    },
    {
     "expr": "increase(nethermind_pending_transactions_hashes_sent{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Sent hashes"
    }
   ]
  },
  {
   "title": "Disconnects (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "increase(nethermind_local_disconnects_total{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} - Local {{reason}}"
    },
    {
     "expr": "increase(nethermind_remote_disconnects_total{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} - Remote {{reason}}"
    }
   ]
  },
  {
   "title": "Eth62, Eth63, Eth65, Eth66 (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "increase(nethermind_incoming_p2p_messages{Instance=~\"$enode\", protocol!=\"snap1\"}[1m])",
     "legendFormat": "{{Instance}} - incoming {{message}} {{protocol}}"
    },
    {
     "expr": "increase(nethermind_outgoing_p2p_messages{Instance=~\"$enode\", protocol!=\"snap1\"}[1m])",
     "legendFormat": "{{Instance}} - outgoing {{message}} {{protocol}}"
    }
   ]
  },
  {
   "title": "Snap Sync (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "increase(nethermind_incoming_p2p_messages{Instance=~\"$enode\", protocol=\"snap1\"}[1m])",
     "legendFormat": "{{Instance}} - incoming {{message}} {{protocol}}"
    },
    {
     "expr": "increase(nethermind_outgoing_p2p_messages{Instance=~\"$enode\", protocol=\"snap1\"}[1m])",
     "legendFormat": "{{Instance}} - outgoing {{message}} {{protocol}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "DB Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_db_reads{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "DB Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_db_writes{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "State Tree",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_state_tree_reads{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Reads"
    },
    {
     "expr": "increase(nethermind_state_reader_reads{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Reader Reads"
    },
    {
     "expr": "increase(nethermind_state_tree_cache{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Cache"
    },
    {
     "expr": "increase(nethermind_state_tree_writes{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Writes"
    }
   ]
  },
  {
   "title": "Storage Tree (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 255 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_storage_tree_reads{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Reads"
    },
    {
     "expr": "increase(nethermind_storage_reader_reads{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} TxPool Reads"
    },
    {
     "expr": "increase(nethermind_storage_tree_cache{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Cache"
    },
    {
     "expr": "increase(nethermind_storage_tree_writes{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Writes"
    }
   ]
  },
  {
   "title": "Code DB (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_code_db_cache{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Cache"
    }
   ]
  },
  {
   "title": "State DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_state_db_in_pruning_writes{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Pruning Writes"
    }
   ]
  },
  {
   "title": "Trie Operations (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(nethermind_tree_node_rlp_decodings{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} RLP.Decode"
    },
    {
     "expr": "increase(nethermind_tree_node_rlp_encodings{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} RLP.Encode"
    },
    {
     "expr": "increase(nethermind_tree_node_hash_calculations{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} Keccak"
    }
   ]
  },
  { "title": "TxPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 283 } },
  {
   "title": "Blob Pool Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 284 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_blob_transaction_count{Instance=\"$enode\"}",
     "legendFormat": "Blob Pool Size"
    }
   ]
  },
  {
   "title": "Pending Blob Tx Added",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 292 },
   "targets": [
    {
     "expr": "nethermind_pending_blob_transactions_added{Instance=\"$enode\"}",
     "legendFormat": "TX Added"
    }
   ]
  },
  {
   "title": "Tx Count",
   "type": "timeseries",
   "description": "Information about incoming transactions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 301 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_transaction_count{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} Count"
    }
   ]
  },
  {
   "title": "Pending Transactions Added",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 309 },
   "targets": [
    {
     "expr": "nethermind_pending_transactions_added{Instance=\"$enode\"}",
     "legendFormat": "TX Added"
    }
   ]
  },
  {
   "title": "DarkPool",
   "type": "timeseries",
   "description": "Unknown transactions in blocks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 318 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_dark_pool_ratio_level1{Instance=\"$enode\"})",
     "legendFormat": "{{Instance}} Level1 (not known)"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_dark_pool_ratio_level2{Instance=\"$enode\"})",
     "legendFormat": "{{Instance}} level2 (not pending)"
    }
   ]
  },
  {
   "title": "1559-type transactions ratio",
   "type": "timeseries",
   "description": "Ratio of 1559-type transactions in the block.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 325 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_eip1559transactions_ratio{Instance=\"$enode\"})",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Incoming transactions (per minute)",
   "type": "timeseries",
   "description": "Information about incoming transactions",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 333 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "increase(nethermind_pending_transactions_received{Instance=\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} received"
    },
    {
     "expr": "increase(nethermind_pending_transactions_discarded{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} discarded"
    },
    {
     "expr": "increase(nethermind_pending_transactions_known{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} discarded already known"
    },
    {
     "expr": "increase(nethermind_pending_transactions_too_low_fee{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} discarded fee too low"
    },
    {
     "expr": "increase(nethermind_pending_transactions_added{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} added"
    },
    {
     "expr": "increase(nethermind_pending_transactions_evicted{Instance=~\"$enode\"}[1m])",
     "legendFormat": "{{Instance}} evicted"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 341 } },
  {
   "title": "DataBase Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 342 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nethermind_db_size{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "Total DataBase Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 342 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(nethermind_db_size{Instance=\"$enode\"}) by (Instance)",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Index Filter Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 352 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nethermind_db_index_filter_size{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "Memtable Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 352 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nethermind_db_memtable_size{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} - {{db}}"
    }
   ]
  },
  {
   "title": "Block Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 362 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nethermind_db_block_cache_size{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} - {{db}}"
    }
   ]
  },
  { "title": "AuRa Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 372 } },
  {
   "title": "Blocks Sealed (total)",
   "type": "stat",
   "description": "Total number of sealed blocks",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 373 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks_sealed{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Failed Block Seals (total)",
   "type": "stat",
   "description": "Total number of failed block seals",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 373 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_failed_block_seals{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Aura Step",
   "type": "timeseries",
   "description": "Current AuRa step",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 373 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_au_ra_step{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Blocks Production Indicator",
   "type": "stat",
   "description": "Indicator if blocks can be produced",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 381 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_can_produce_blocks{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Reported Malicious Misbehaviour",
   "type": "stat",
   "description": "Number of reported malicious misbehaviour validators",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 381 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_reported_malicious_misbehaviour{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Sealed Transactions",
   "type": "timeseries",
   "description": "Number of sealed transactions generated by engine",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 381 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_sealed_transactions{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Reported Benign Misbehaviour",
   "type": "stat",
   "description": "Number of reported benign misbehaviour validators",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 389 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_reported_benign_misbehaviour{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Validators Count",
   "type": "stat",
   "description": "Number of current AuRa validators",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 389 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_validators_count{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "RANDAO Reveal Number",
   "type": "timeseries",
   "description": "RANDAO number of reveal number transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 389 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_reveal_number{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "POSDAO Emit Initiate Change",
   "type": "timeseries",
   "description": "POSDAO number of emit init change transactions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 397 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_emit_initiate_change{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "RANDAO Commit Hash Transaction",
   "type": "timeseries",
   "description": "RANDAO number of commit hash transactions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 397 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nethermind_commit_hash_transaction{Instance=\"$enode\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  }
 ]
}